export const COUNTRIES = [
  { code: '54', name: 'Argentina', flag: '🇦🇷' },
  { code: '598', name: 'Uruguay', flag: '🇺🇾' },
  { code: '56', name: 'Chile', flag: '🇨🇱' },
  { code: '595', name: 'Paraguay', flag: '🇵🇾' },
  { code: '591', name: 'Bolivia', flag: '🇧🇴' },
  { code: '55', name: 'Brasil', flag: '🇧🇷' },
  { code: '57', name: 'Colombia', flag: '🇨🇴' },
  { code: '51', name: 'Perú', flag: '🇵🇪' },
  { code: '52', name: 'México', flag: '🇲🇽' },
  { code: '58', name: 'Venezuela', flag: '🇻🇪' },
  { code: '593', name: 'Ecuador', flag: '🇪🇨' },
  { code: '34', name: 'España', flag: '🇪🇸' },
  { code: '1', name: 'Estados Unidos', flag: '🇺🇸' },
  { code: '39', name: 'Italia', flag: '🇮🇹' },
  { code: '33', name: 'Francia', flag: '🇫🇷' },
  { code: '49', name: 'Alemania', flag: '🇩🇪' },
  { code: '44', name: 'Reino Unido', flag: '🇬🇧' },
  { code: '351', name: 'Portugal', flag: '🇵🇹' },
  { code: '81', name: 'Japón', flag: '🇯🇵' },
  { code: '82', name: 'Corea del Sur', flag: '🇰🇷' },
  { code: '86', name: 'China', flag: '🇨🇳' },
  { code: '61', name: 'Australia', flag: '🇦🇺' },
  { code: '1', name: 'Canadá', flag: '🇨🇦' },
  { code: '506', name: 'Costa Rica', flag: '🇨🇷' },
  { code: '507', name: 'Panamá', flag: '🇵🇦' },
  { code: '503', name: 'El Salvador', flag: '🇸🇻' },
  { code: '502', name: 'Guatemala', flag: '🇬🇹' },
  { code: '504', name: 'Honduras', flag: '🇭🇳' },
  { code: '505', name: 'Nicaragua', flag: '🇳🇮' },
  { code: '53', name: 'Cuba', flag: '🇨🇺' },
  { code: '1', name: 'Puerto Rico', flag: '🇵🇷' },
  { code: '1', name: 'República Dominicana', flag: '🇩🇴' },
  { code: '41', name: 'Suiza', flag: '🇨🇭' },
  { code: '32', name: 'Bélgica', flag: '🇧🇪' },
  { code: '31', name: 'Países Bajos', flag: '🇳🇱' },
  { code: '43', name: 'Austria', flag: '🇦🇹' },
  { code: '46', name: 'Suecia', flag: '🇸🇪' },
  { code: '47', name: 'Noruega', flag: '🇳🇴' },
  { code: '45', name: 'Dinamarca', flag: '🇩🇰' },
  { code: '358', name: 'Finlandia', flag: '🇫🇮' },
  { code: '30', name: 'Grecia', flag: '🇬🇷' },
  { code: '90', name: 'Turquía', flag: '🇹🇷' },
  { code: '972', name: 'Israel', flag: '🇮🇱' },
  { code: '966', name: 'Arabia Saudita', flag: '🇸🇦' },
  { code: '971', name: 'Emiratos Árabes', flag: '🇦🇪' },
  { code: '27', name: 'Sudáfrica', flag: '🇿🇦' },
  { code: '234', name: 'Nigeria', flag: '🇳🇬' },
  { code: '20', name: 'Egipto', flag: '🇪🇬' },
  { code: '6Morocco', name: 'Marruecos', flag: '🇲🇦', codeValue: '212' }, // Fixed manually
].map(c => ({ ...c, code: (c as any).codeValue || c.code }))
  .sort((a, b) => a.name.localeCompare(b.name))

// Move Argentina to the top
export const SORTED_COUNTRIES = [
  { code: '54', name: 'Argentina', flag: '🇦🇷' },
  ...COUNTRIES.filter(c => c.code !== '54')
]
